Repository TeamCafebara/Cafebara-iOS, pull requests merged in 2024-03, with the labels that each got.

#6 [Setting] #5 - 폰트 및 네트워크 세팅
  Cafebara-iOS/.swiftlint.yml
  Cafebara-iOS/Cafebara-iOS.xcodeproj/project.pbxproj
  Cafebara-iOS/Cafebara-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Cafebara-iOS/Cafebara-iOS/Global/Extensions/UIImageView+.swift
  Cafebara-iOS/Cafebara-iOS/Global/Literals/FontLiterals.swift
  Cafebara-iOS/Cafebara-iOS/Global/Protocols/UICollectionViewRegisterable.swift
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Font/SUIT-Bold.ttf
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Font/SUIT-Medium.ttf
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Font/SUIT-Regular.ttf
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Font/SUIT-SemiBold.ttf
  Cafebara-iOS/Cafebara-iOS/Info.plist
  Cafebara-iOS/Cafebara-iOS/Network/API/Home/HomeAPI.swift
  Cafebara-iOS/Cafebara-iOS/Network/APIService/Home/HomeTarget.swift
  Cafebara-iOS/Cafebara-iOS/Network/Base/APIConstant.swift
  Cafebara-iOS/Cafebara-iOS/Network/Base/BaseTargetType.swift
  Cafebara-iOS/Cafebara-iOS/Network/Base/GeneralResponse.swift
  Cafebara-iOS/Cafebara-iOS/Network/Base/NetworkLoggerPlugin.swift
  Cafebara-iOS/Cafebara-iOS/Network/Base/URLConstant.swift
  Cafebara-iOS/Cafebara-iOS/Network/Enviornment/Config.swift
Labels: ⚙️Setting, 🦖아라

#10 [Feat] #9 - 공용 컴포넌트 구현
  Cafebara-iOS/Cafebara-iOS.xcodeproj/project.pbxproj
  Cafebara-iOS/Cafebara-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Cafebara-iOS/Cafebara-iOS/Global/Extensions/UIButton+.swift
  Cafebara-iOS/Cafebara-iOS/Global/Extensions/UILabel+.swift
  Cafebara-iOS/Cafebara-iOS/Global/Literals/SizeLiterals.swift
  Cafebara-iOS/Cafebara-iOS/Global/Literals/StringLiterals.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Common/CustomAlert/CustomAlertView.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Common/CustomButton/CustomButton.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Common/CustomNavigation/CustomNavigationView.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Common/CustomToastMessage/CustomToastMessage.swift
Labels: ☕️Feat, 🎨UI, 🦖아라

#15 [Feat] #11 - Custom TabBar 구현
  Cafebara-iOS/Cafebara-iOS.xcodeproj/project.pbxproj
  Cafebara-iOS/Cafebara-iOS/Global/Literals/StringLiterals.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Common/CustomTabBar/TabBarController.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Common/CustomTabBar/TabBarItem.swift
Labels: ☕️Feat, 🎨UI, 🐙가현

#18 [Feat] #13 - 로그인 뷰 UI 구현
  Cafebara-iOS/Cafebara-iOS.xcodeproj/project.pbxproj
  Cafebara-iOS/Cafebara-iOS/Cafebara-iOS.entitlements
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Assets.xcassets/logInImage1.imageset/Contents.json
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Assets.xcassets/logInImage1.imageset/Group 1171276075.svg
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Assets.xcassets/logInImage2.imageset/2.svg
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Assets.xcassets/logInImage2.imageset/Contents.json
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Assets.xcassets/logInImage3.imageset/3.svg
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Assets.xcassets/logInImage3.imageset/Contents.json
  Cafebara-iOS/Cafebara-iOS/Info.plist
  Cafebara-iOS/Cafebara-iOS/Network/Data/Onboarding/LoginImageDto.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Splash/LogInScene/Cell/LoginCollectionViewCell.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Splash/LogInScene/View/LoginView.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Splash/LogInScene/ViewController/LoginViewController.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Splash/LogInScene/ViewModel/LogInViewModel.swift
Labels: ☕️Feat, 🎨UI, 🐯민지

#17 [Feat] #12 - 회원가입뷰 ui 구현
  .gitignore
  Cafebara-iOS/Cafebara-iOS.xcodeproj/project.pbxproj
  Cafebara-iOS/Cafebara-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Cafebara-iOS/Cafebara-iOS/Application/AppDelegate.swift
  Cafebara-iOS/Cafebara-iOS/Application/SceneDelegate.swift
  Cafebara-iOS/Cafebara-iOS/Cafebara-iOS.entitlements
  Cafebara-iOS/Cafebara-iOS/Global/Extensions/String+.swift
  Cafebara-iOS/Cafebara-iOS/Global/Literals/StringLiterals.swift
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Assets.xcassets/ColorBara/Blue75.colorset/Contents.json
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Assets.xcassets/ColorBara/ErrorBara.colorset/Contents.json
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Assets.xcassets/IconBara/profile.imageset/Contents.json
  Cafebara-iOS/Cafebara-iOS/Global/Resources/Assets.xcassets/IconBara/profile.imageset/profile.png
  Cafebara-iOS/Cafebara-iOS/Info.plist
  Cafebara-iOS/Cafebara-iOS/Network/Data/LoginImageDto.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Common/UIComponents/CustomAlertView.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Common/UIComponents/CustomButton.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Common/UIComponents/CustomNavigationView.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Common/UIComponents/CustomTextField.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Common/UIComponents/CustomToastMessage.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Home/HomeScene/ViewController/ViewController.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/InviteCodeScene/View/InviteCodeView.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/InviteCodeScene/ViewController/InviteCodeViewController.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/LoginScene/Cell/LoginCollectionViewCell.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/LoginScene/View/LoginView.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/LoginScene/ViewController/LoginViewController.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/LoginScene/ViewModel/LoginViewModel.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/NameInputScene/View/NameInputView.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/NameInputScene/ViewController/NameInputViewController.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/RegisterCompleteScene/View/RegisterCompleteView.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/RegisterCompleteScene/ViewController/RegisterCompleteViewController.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/RoleChoiceScene/View/RoleChoiceView.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/RoleChoiceScene/ViewController/RoleChoiceViewController.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/RoleChoiceScene/ViewModel/OnboardingRegisterViewModel.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/StoreInputScene/View/StoreInputView.swift
  Cafebara-iOS/Cafebara-iOS/Presentation/Onboarding/StoreInputScene/ViewController/StoreInputViewController.swift
Labels: ☕️Feat, 🎨UI, 🦖아라
